### ISSUE TITLE
Make discover show progress

### ISSUE THREAD

**Issue by nasht00** [mixu/gr#32]
I typed discover a while ago, and I'm still waiting.
Is it still searching? Is it stuck? Did it crash?
I wish there was some progress indication just to see that it's still working...

**Comment by mkstix6** [comment]
Ye i'm wondering the same thing today. Did yours complete in the end or is it forever and ever and ever?

**Comment by mkstix6** [comment]
Also i tried typing `gr` just to see if it installed ok but i got nothing back. It's just reassuring to see something like git's `git` command.

**Comment by mixu** [comment]
fixed! When I originally wrote `gr`, I didn't realize that people could have super deep `~` paths. Now `gr discover` accepts path arguments, shows progress and recurses to a maximum of five levels deep in search of git directories...

**Comment by mkstix6** [comment]
ahh amazing! Yes that's perfect. I realised in the final report gr was scanning my whole hard disk but I couldn't work out how to contain it to my project folder. Thanks.

**Comment by coderjoe** [comment]
@mixu I'm glad I built my gr config before this change. My home is large, contains symlinks to source, and the actual git repos are exactly 6 levels deep. ;)

**Comment by mixu** [comment]
hmm, I wonder if I should make discover not follow symlinks - seems like there are valid cases where it should, then again the reason @mkstix6's gr scans the whole drive is probably a symlink somewhere... 

I'll probably just keep the follow-symlinks behavior for now, since at least with the progress output one can more effectively diagnose what is going on...

As for discovering 6 folders deep, one can work around the max-depth limitation by explicitly passing a path that's deeper thanks to that patch you wrote @coderjoe :)

**Comment by mixu** [comment]
published as `v0.5.0`

**Comment by coderjoe** [comment]
@mixu good point! :+1:
